services:
  ros2:
    container_name: ros2
    image: elkuno213/ros2:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workspaces/ros2-ws
    environment:
      - DISPLAY=ros2-novnc:0.0
    networks:
      - ros2-network
    tty: true
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1

  ros2-novnc:
    container_name: ros2-novnc
    image: "theasp/novnc:latest"
    environment:
      - DISPLAY_WIDTH=1800
      - DISPLAY_HEIGHT=1012
      - RUN_XTERM=no
      - RUN_FLUXBOX=yes
    ports:
      - "8080:8080" # http://localhost:8080/vnc.html
    networks:
      - ros2-network

networks:
  ros2-network:
    name: ros2-network
